name: .NET Core Build and Test

on:
  push:
    branches: 
      - develop
  pull_request:
    branches: 
      - release
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.201'
    - name: Install dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --configuration Release --no-restore
    - name: Test
      run: dotnet test tests --verbosity normal
    - name: Build the Docker image
      run: docker build . --file ./Dockerfile --tag localbuild/openrmf-api-template:latest
    - uses: anchore/scan-action@v2
      with:
        image: "localbuild/openrmf-api-template:latest"
        fail-build: false
        debug: true
    - name: anchore inline scan JSON results
      run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
